apiVersion: v1
kind: Secret

# Secret for env vars
metadata:
  name: logstashsecret
type: Opaque
stringData:
  {{- range $name, $value := .Values.logstashSecrets }}
  {{- if not (empty $value) }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}