apiVersion: v1
kind: Service
# Ports for service
metadata:
  name: {{.Values.appName}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: web
    - port: {{.Values.beatservice.port}}
      targetPort: {{.Values.beatservice.port}}
      protocol: TCP
      name: beat
  selector:
    app: {{.Values.nameOverride}}
