{{- if .Values.esConfig }}
---
apiVersion: v1
kind: ConfigMap
# Creates elasticsearch.yml file
metadata:
  name: {{ .Values.appName }}-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ .Values.appName }}"
data:
{{- range $path, $config := .Values.esConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}