apiVersion: storage.k8s.io/v1
kind: StorageClass
# Creates stprage class for elasticsearch data volume
metadata:
  name: {{.Values.esDataStorageClassName}}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer