apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.esDataVolumeClaimName}}
spec:
  storageClassName: {{.Values.esDataStorageClassName}}
  volumeName: {{ .Values.esDataVolumeName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
