apiVersion: v1
kind: Secret
# Creates secret for any variables in extraEnvs
metadata:
  name: elasticsecret
type: Opaque
stringData:
  {{- range $name, $value := .Values.extraEnvs }}
  {{- if not (empty $value) }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}