{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
# Service account info
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}