apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  # Set replica amount if no autoscaling policy
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  # Set selector
  selector:
    matchLabels:
      app: {{ .Values.appName }}

  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      # Creates service account
      serviceAccountName: {{ .Values.serviceAccount.name }}

      # Declares volumes for container
      volumes:
        # Volume for kibana.yml file
        - name: kibana-config
          configMap:
            name: {{ .Values.appName }}-config    

      # Main Container          
      containers:
        - name: {{ .Values.appName }}
          
          # Image info
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # Env var for secrets - not used in this example, but can be added to from kibanaSecrets in values file
          envFrom:
            - secretRef:
                name: kibanasecrets
          
          # Mounts for volumes
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml                
