apiVersion: v1
kind: Secret
# Secret for env var
metadata:
  name: kibanasecrets
type: Opaque
stringData:
  {{- range $name, $value := .Values.kibanaSecrets }}
  {{- if not (empty $value) }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}