apiVersion: v1
kind: Service
# Service and ports
metadata:
  name: {{.Values.appName}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: web
  selector:
    app: {{.Values.appName}}
