# Default values for test-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Name of service
appName: "elasticsearch-dev"

# Name of volume backing elasticsearch service
esDataVolumeClaimName: "elasticsearch-dev-volume"
esDataVolumeName: "elasticsearch-data"
esDataStorageClassName: "elasticsearch-storage-class"
esDataFolderPath: "/var/lib/docker/volumes/esData/"

# Env Vars for running on local machine, dont use these in prod env
extraEnvs:
  - name: "discovery.type"
    value: "single-node"
  - name: "ES_JAVA_OPTS"
    value: "-Xms6000m -Xmx6000m"

# Autoscaling info
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20

replicaCount: 1

# Image info
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
  pullPolicy: IfNotPresent
  tag: "6.8.2"

# Enables basic x-pack security with elasticsearch.yml
# needs network host 0.0.0.0 to accept connections from other containers in cluster
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    network.host: 0.0.0.0

# Create a service account for elasticsearch service on kubernetes
serviceAccount:
  name: "elasticsearch-service-account"
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template

# Runs service on port 9200/9300 of container
service:
  type: ClusterIP
  port: 9200

transportservice:
  type: ClusterIP
  port: 9300
