apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.volumeClaimName}}
spec:
  storageClassName: {{.Values.storageClassName}}
  volumeName: logs-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
