{{- if .Values.filebeatConfig }}
---
apiVersion: v1
kind: ConfigMap
# Creats config map for filebeat.yml
metadata:
  name: {{ .Values.appName }}-config
  labels:
    app: "{{ .Values.appName }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.filebeatConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}