apiVersion: v1
kind: Secret

# Creates secret
metadata:
  name: filebeatsecret
type: Opaque
stringData:
  {{- range $name, $value := .Values.filebeatSecrets }}
  {{- if not (empty $value) }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}